### PR TITLE
changed CSS and JavaScript

### PR DESCRIPTION
**Pull request by vidushi1012**
I have changed the CSS and JavaScript code to make it look more attractive. Also, I have added two new containers namely completed and not completed to hold the completed and incomplete tasks respectively.

### CODE REVIEW

**Review by abhishekjha812 — COMMENTED** [review]
Looks cool !
Thanks for your contribution :)

**Comment by abhishekjha812** [comment]
Would you like to work on the project below too ? 
https://github.com/abhishekjha812/autenjo3

**Comment by vidushi1012** [comment]
> Would you like to work on the project below too? https://github.com/abhishekjha812/autenjo3

Yeah, sure it looks very good. I will try my best to make some good contributions.

**Comment by abhishekjha812** [comment]
Great thanks 👍

**Pull request merged**
